### ISSUE TITLE
gr_timesheet_sheet v11 relativedelta unsupported type

### ISSUE THREAD

**Issue by ACouasnonPerso** [OCA/timesheet#262]
Hello, I am on Odoo 11 under a docker context. I have dowload matrix_2d and hr_timesheet_sheet from the 11.0 branch.
When i go to "Timesheet" and then to "My Timesheet sheet" and finally i push "create" button, this error is raised :
```
  File "/usr/lib/python3/dist-packages/dateutil/relativedelta.py", line 393, in __radd__
    return self.__add__(other)
  File "/usr/lib/python3/dist-packages/dateutil/relativedelta.py", line 351, in __add__
    raise TypeError("unsupported type for add operation")
TypeError: unsupported type for add operation
```
I don't have any other module on my database, juste timesheet.
Do you have any hint to solve this issue ?
Thank for the time you will take to answer me.

**Comment by ACouasnonPerso** [comment]
The solution for me was to update the date: 
pip3 install python-dateutil --upgrade

This then works when creating, a new error appears when saving: 
```
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "name" of relation "hr_timesheet_sheet" does not exist
LINE 1: INSERT INTO "hr_timesheet_sheet" ("id", "name", "state", "da...
```
Indeed there is no "name" column in this table... is this module stable in version 11???

**Comment by pedrobaeza** [comment]
Yes, it is. You can check that is working in https://runbot.odoo-community.org/runbot/117/11.0

Your problem should be an improper installation of the module due to the error on the lib. Please start again with correct libraries.

**Comment by ACouasnonPerso** [comment]
Thank you for your answer, effectively it works very well on the demo link.
Can you be a little more specific ? which libraries do you think about ?

**Comment by pedrobaeza** [comment]
python-dateutil, as you already mentioned. I mean you need a clean proper deployment before. Check https://www.odoo.com/documentation/11.0/setup/install.html.

**Comment by ACouasnonPerso** [comment]
I understand your answer, that makes sense. But from my point of view I use the right version of odoo 11, here is my compound docker: 
```
version:'2' version
services:
  odoo:
    image: odoo:11
    restart: always
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - ./addons:/mnt/extra-addons

  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=****
      - POSTGRES_USER=****
      - POSTGRES_DB=postgres
      
  pgadmin:
    image: thajeztah/pgadmin4
    restart: always
    ports:
      - 5050:5050
    links:
      - db
```
I have downloaded version 11.0.2.2.0.0.0 of timesheet_sheet.
